### ISSUE TITLE
SVG file `/usr/share/xxkb/en.svg': Operation not supported

### ISSUE THREAD

**Issue by powerman** [ramok/xxkb#1]
Can you please take a look at https://bugs.gentoo.org/685646?

It looks like your fork is the only alive xxkb today, and it have same issue.

**Comment by ramok** [comment]
Can you show build log?

**Comment by ramok** [comment]
In debian with librsvg 2.44.10 work good. It was [fixed in librsvg 2.42.3](https://abi-laboratory.pro/index.php?view=changelog&l=librsvg&v=2.42.6).

> gitlab#198 - Fix: Make rsvg_pixbuf_from_file() and its derived functions work again.  Now we have tests for the whole public API.

**Comment by powerman** [comment]
Thanks!
